[package]
name = "vertam"
version = "0.1.0"
authors = ["Elias Dilem dos Santos <eliasdilem@outlook.com>"]

[dependencies]
imagesize = "0.5.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi"] }
